# Generated by Django 3.0.7 on 2020-06-16 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stokkapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppinglist',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='useritem',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='useritem',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='useritem',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='useritem',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userlistitem',
            old_name='shopping_list_id',
            new_name='shopping_list',
        ),
    ]
