# Generated by Django 3.0.7 on 2020-06-18 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stokkapp', '0002_auto_20200616_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useritem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stokkapp.Category'),
        ),
        migrations.AlterField(
            model_name='useritem',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stokkapp.Location'),
        ),
        migrations.AlterField(
            model_name='useritem',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stokkapp.Store'),
        ),
        migrations.AlterField(
            model_name='useritem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
