# Generated by Django 3.0.7 on 2020-06-22 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stokkapp', '0004_auto_20200618_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userlistitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stokkapp.Item'),
        ),
        migrations.AlterField(
            model_name='userlistitem',
            name='shopping_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stokkapp.ShoppingList'),
        ),
    ]
